package com.example.ruler.noteapplication.Data;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_NOTE_TAG".
*/
public class JoinNoteTagDao extends AbstractDao<JoinNoteTag, Long> {

    public static final String TABLENAME = "JOIN_NOTE_TAG";

    /**
     * Properties of entity JoinNoteTag.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NoteId = new Property(1, Long.class, "noteId", false, "NOTE_ID");
        public final static Property TagId = new Property(2, Long.class, "tagId", false, "TAG_ID");
    }


    public JoinNoteTagDao(DaoConfig config) {
        super(config);
    }
    
    public JoinNoteTagDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_NOTE_TAG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NOTE_ID\" INTEGER," + // 1: noteId
                "\"TAG_ID\" INTEGER);"); // 2: tagId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_NOTE_TAG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinNoteTag entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long noteId = entity.getNoteId();
        if (noteId != null) {
            stmt.bindLong(2, noteId);
        }
 
        Long tagId = entity.getTagId();
        if (tagId != null) {
            stmt.bindLong(3, tagId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinNoteTag entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long noteId = entity.getNoteId();
        if (noteId != null) {
            stmt.bindLong(2, noteId);
        }
 
        Long tagId = entity.getTagId();
        if (tagId != null) {
            stmt.bindLong(3, tagId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinNoteTag readEntity(Cursor cursor, int offset) {
        JoinNoteTag entity = new JoinNoteTag( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // noteId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // tagId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinNoteTag entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNoteId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTagId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinNoteTag entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinNoteTag entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinNoteTag entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
